In [1]:
import tensorflow as tf 
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import Common_Functions as cf 


In [2]:
df_pions = np.array(pd.read_csv('/home/sean/Documents/Work/Level 4/Level-4-Masters-Project/Djuna_Data_Generation_Notebook/noshift1.csv',header = None))
train_x, train_y = cf.data_normaliser(df_pions[:-1000,:8]), df_pions[:-1000,-1]
val_x, val_y = cf.data_normaliser(df_pions[-1000:,:8]), df_pions[-1000:,-1]

In [3]:
opt = keras.optimizers.Adam(learning_rate= 0.005, beta_1 = 0.7, beta_2= 0.99)

In [19]:
def layers_tester(size_range,size_spacing,layer_range,repeats):
    min_size, max_size = size_range
    if (max_size-min_size)/size_spacing == int: 
        raise Exception('Spacing Must Be Integer U fuckwit')
    else:
        size_steps = int((max_size-min_size)/size_spacing)
        size_list = np.linspace(int(min_size),int(max_size),size_steps)
        layer_range_list = range(1,1+layer_range)
        min_mape = np.zeros((size_steps,layer_range,repeats)) ###Axis 0:Size of Layers 1:Number of Layers 3:Number of repeats to take average over. 
        for i in range(size_steps):
            for j in range(layer_range):
                loop_layer_shape = size_list[i]*np.ones((layer_range_list[j]))
                print(loop_layer_shape)


In [16]:
layers_tester((0,10),2,5,5)

5
[0.]
[0. 0.]
[0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[2.5]
[2.5 2.5]
[2.5 2.5 2.5]
[2.5 2.5 2.5 2.5]
[2.5 2.5 2.5 2.5 2.5]
[5.]
[5. 5.]
[5. 5. 5.]
[5. 5. 5. 5.]
[5. 5. 5. 5. 5.]
[7.5]
[7.5 7.5]
[7.5 7.5 7.5]
[7.5 7.5 7.5 7.5]
[7.5 7.5 7.5 7.5 7.5]
[10.]
[10. 10.]
[10. 10. 10.]
[10. 10. 10. 10.]
[10. 10. 10. 10. 10.]
